### ISSUE TITLE
Proper packaging

### ISSUE THREAD

**Issue by tshort** [davidagold/MetaMerge.jl#2]
This still needs a few more things for proper packaging. Off the top of my head:
- LICENSE.md -- MIT preferred
- Make a /src directory, and put MetaMerge.jl there.

Look around at other packages for organization. See the docs, too:

https://julia.readthedocs.org/en/latest/manual/packages/#package-development

**Comment by davidagold** [comment]
@tshort Thank you for these resources. I really appreciate your helping out an enthusiastic beginner. (TBH I had always wondered what, precisely, a "git" is before reading that section!) Now I need to figure out everything going on in there, but I intend to get everything according to code asap.

**Comment by davidagold** [comment]
@tshort I think the basics here are in order... Would you mind checking if `Pkg.clone("git://github.com/davidagold/MetaMerge.jl.git)` work for you? Would I be too quick in closing this issue now? Thank you!

**Comment by tshort** [comment]
Looks good.
